services:
  crack-detector:
    build: .
    volumes:
      - ./input:/app/input
      - ./output:/app/output
      - ./output_backup:/app/output_backup
    entrypoint: ["python", "detect.py"]
    command: []
